title: Xincheng Li
description: "Brief description of your research and projects"
theme: jekyll-theme-minimal  # or any other GitHub Pages supported theme

github_username: lixc1
email: lixc1sc@gmail.com
